use crate::model::*;
use anyhow::Result;
use rusqlite::Connection;
use std::path::Path;

const GENERATED_HEADER: &str =
    "<!-- GENERATED by garnish; edits are overwritten. See docs/data-model.md -->\n\n";

/// Regenerate the human-readable projections for one project (ADR-0006).
pub fn write_all(conn: &Connection, project: &Project) -> Result<()> {
    let root = Path::new(&project.root_path);
    let dir = crate::paths::projection_dir(root);
    std::fs::create_dir_all(dir.join("runs"))?;

    // PROJECT.md
    let project_md = format!(
        "{GENERATED_HEADER}# {name}\n\n- id: `{id}`\n- kind: {kind}\n- root: `{root}`\n- created: {created}\n\n## Policy\n\n```json\n{policy}\n```\n",
        name = project.name,
        id = project.id,
        kind = project.kind,
        root = project.root_path,
        created = project.created_at,
        policy = serde_json::to_string_pretty(&project.policy)?,
    );
    std::fs::write(dir.join("PROJECT.md"), project_md)?;

    // TASKS.md
    let tasks = crate::store::task_list(conn, Some(&project.id))?;
    let mut md = format!("{GENERATED_HEADER}# Tasks — {}\n\n", project.name);
    for section in [
        ("Active", vec!["leased", "planning", "awaiting_approval", "running", "verifying", "review"]),
        ("Ready", vec!["ready", "draft"]),
        ("Blocked / paused", vec!["blocked", "paused"]),
        ("Done / closed", vec!["completed", "failed", "cancelled", "superseded"]),
    ] {
        let items: Vec<&Task> = tasks
            .iter()
            .filter(|t| section.1.contains(&t.status.as_str()))
            .collect();
        if items.is_empty() {
            continue;
        }
        md.push_str(&format!("## {}\n\n", section.0));
        for t in items {
            md.push_str(&format!(
                "- `{}` **{}** [{}] — {}\n",
                t.id,
                t.title,
                t.status.as_str(),
                t.spec.goal
            ));
        }
        md.push('\n');
    }
    std::fs::write(dir.join("TASKS.md"), md)?;

    // agents/ stubs pointing back to canonical context.
    let agents = dir.join("agents");
    std::fs::create_dir_all(&agents)?;
    let stub = format!(
        "{GENERATED_HEADER}This project is managed by Harness Garnish.\n\nCanonical context: `.harness-garnish/PROJECT.md` and `.harness-garnish/TASKS.md`.\nDo not duplicate state here; read those files.\n"
    );
    std::fs::write(agents.join("AGENTS.md"), &stub)?;
    std::fs::write(agents.join("CLAUDE.md"), &stub)?;
    Ok(())
}

/// Write the handoff packet for a task (spec §handoff) as both the canonical
/// JSON (run evidence) and the HANDOFF.md projection.
pub fn write_handoff(
    project: &Project,
    task: &Task,
    packet: &serde_json::Value,
    evidence_dir: &Path,
) -> Result<()> {
    std::fs::create_dir_all(evidence_dir)?;
    std::fs::write(
        evidence_dir.join("handoff.json"),
        serde_json::to_string_pretty(packet)?,
    )?;
    let dir = crate::paths::projection_dir(Path::new(&project.root_path));
    std::fs::create_dir_all(&dir)?;
    let md = format!(
        "{GENERATED_HEADER}# Handoff — {title}\n\ntask: `{id}` status: {status}\n\n```json\n{packet}\n```\n",
        title = task.title,
        id = task.id,
        status = task.status.as_str(),
        packet = serde_json::to_string_pretty(packet)?,
    );
    std::fs::write(dir.join("HANDOFF.md"), md)?;
    Ok(())
}
